### ISSUE TITLE
No handler found for the command: 'red_menu' (Ubuntu)

### ISSUE THREAD

**Issue by SteeveGit** [red/VScode-extension#1]
Under Ubuntu(64 bit) 14.04, when pressing F2,  I got:
No handler found for the command: 'red_menu'. An extension might be missing an activation event.

**Comment by SteeveGit** [comment]
Got this log in the developer tool:

```
[Extension Host] Here is the error stack:  Error: Cannot find module '/home/a/.vscode/extensions/red-language/out/src/extension'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.N.n._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:17:18321)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Function.t [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:4:1298)
    at d (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:26361)
    at t._doActualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:8)
    at t._actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:31725)
    at t.e._activateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:2228)
```

**Comment by SteeveGit** [comment]
Got it, modified package.json:
Lin 64: `"main": "./src/extension.ts",`

But I wonder... why only on Linux?. No one else reported it back previously.

**Comment by red-eco** [comment]
I add files from yocode for debugging typescript.
You can try again (remove old and install new extension).
